create:
  name: input_noising_attack
  num_classes: 10
  mean: 0.15
  std: 0.0

remove:
  name: input_noising_removal

dataset:
  name: CIFAR10DataLoader
  subset: attacker
  root: ~/.wrt/data
  batch_size: 64
  image_size: 32
  num_workers: 2

true_labels: True
name: input_noising2
output_dir: outputs/cifar10/attacks/input_noising2/