wm_scheme:
  name: wm_adi
  num_classes: 10

embed:
  name: wm_adi_embed
  boost_factor: 10
  keylength: 100
  patience: 200
  epochs: 600
  check_every_n_batches: 200

source_model:
  name: densenet_cifar
  image_size: 32
  num_classes: 10

optimizer:
  name: SGD
  lr: 0.1
  weight_decay: 5.e-4
  momentum: 0.9
  nesterov: true

wm_dataset:
  name: AdiTriggerDataLoader
  root: ~/.wrt/data
  batch_size: 2
  image_size: 32
  num_workers: 4

dataset:
  name: CIFAR10DataLoader
  subset: defender
  root: ~/.wrt/data
  batch_size: 128
  image_size: 32
  num_workers: 4

name: adi
output_dir: outputs/cifar10/wm/adi/


